### ISSUE TITLE
Create phase 2 design guidelines for modal component

### ISSUE THREAD

**Issue by Blackbaud-AlexKingman** [blackbaud/skyux-modals#102]

**Comment by blackbaud-johnly** [comment]
We have some existing guidance in place at https://developer.blackbaud.com/skyux/components/modal#ux-guidelines that we can use as a starting point.

**Comment by Blackbaud-AlexKingman** [comment]
@blackbaud-johnly can this be closed? We have content live here: https://developer.blackbaud.com/skyux-modals/docs/modal

**Comment by blackbaud-johnly** [comment]
Sorry for the slow response, @Blackbaud-AlexKingman. I linked to those existing UX guidelines as a starting point for phase 2 docs, but this content probably still needs a review from Design to see what we want to change, what we want to add, and where we should include images. The intent for this was for that phase 2 work, not for the initial migration of the existing docs. That said, given that we are switching from GitHub to ADO, I think we can close this issue since we know that we'll have multiple component docs in this situation or in the situation where they have no Design guidelines at all. I'll go ahead and close this issue, but let me know what you think we should do to track the work to create true phase 2 Design guidelines.
