### ISSUE TITLE
HostListener for document:click not working in 3.0.2

### ISSUE THREAD

**Issue by Blackbaud-LouisPujol** [blackbaud/skyux-modals#43]
### Expected behavior
Modal components, as well as any nested components, should be able to respond to document:click events

### Actual behavior
After upgrading to 3.0.2, any HostListeners for document:click are not fired when a user clicks on or outside of a modal component

### Steps to reproduce
Create a modal component such as the one below
```
import { Component, HostListener } from '@angular/core';

@Component({
    selector: 'test-modal',
    template: '<sky-modal><sky-modal-content></sky-modal-content></sky-modal>'
})

export class TestModalComponent {
    constructor() {}

    @HostListener('document:click')
    public onDocumentClick() {
        console.log('user clicked the DOM');
    }

    @HostListener('click')
    public onClick() {
        console.log('user clicked inside the modal');
    }
}
```
Click anywhere in the modal and the `onClick` event fires, however the `onDocumentClick` does not fire.
Click anywhere not in the modal and neither of the HostListeners fire

Downgrading to 3.0.1 fixes the issue and fires `onDocumentClick` in both cases described above.

### Impact
This greatly impacts any functionality around detecting if a user clicks away from a component inside of a modal.

**Comment by Blackbaud-SteveBrush** [comment]
@Blackbaud-LouisPujol This was a deliberate change because we had many scenarios where we didn't want click events to "escape" from the modal and propagate to the document (see [CHANGELOG](https://github.com/blackbaud/skyux-modals/blob/master/CHANGELOG.md#303-2019-04-26)). 

However, in your specific use-case (RE: "detecting if a user clicks away from a component inside of a modal"), this is still possible if you watch for click events on an element within the modal instead of the `document` (maybe `.sky-modal-content`?).
