### ISSUE TITLE
Confirming a task from the confirm modal from another modal, the first modal stays open too long

### ISSUE THREAD

**Issue by blackbaud-BenWong** [blackbaud/skyux-modals#69]
### Expected behavior
When clicking on the confirm button from the confirm modal, the modal that launched the confirm modal should close instantly.

### Actual behavior
When clicking on the confirm button from the confirm modal, the modal that launched the confirm modal stays open for a split second, allowing the user to accidentally launch the confirm modal again.

### Steps to reproduce

1. Launch a confirm modal from another modal.
2. Click enter twice quickly 

### Severity
The consumer could disable the original button that launched the modal.

### Impact
Could cause users to confirm the wrong thing. For example, for Recurring Gifts, the user confirms the number of gifts to skip. If the original confirmation is to skip 10 gifts, but hitting the button twice, it could cause skipping 20 gifts.

This was reported by Lance Melton and Ali Rashed.

![Screen Shot 2019-10-02 at 2 17 13 PM](https://user-images.githubusercontent.com/23264858/66076650-462a2680-e52c-11e9-924a-235282f87823.png)

**Comment by blackbaud-BenWong** [comment]
@Blackbaud-AliRashed

**Comment by Blackbaud-SteveBrush** [comment]
This would probably be too much of a "niche" setup to bake the functionality into the parent modal. Instead, the workaround should be to either disable the submit button on the parent modal, or launch a Wait component until the confirm's process is complete. Is that possible on your end?

**Comment by Blackbaud-AliRashed** [comment]
@Blackbaud-SteveBrush Our current workaround is disabling the submit button on the parent modal- it works pretty well!

I think Lance had the concern that other teams might not remember to disable the button (since it was caught during a demo since Lance does a lot of accessibility work and is used to thinking about keyboard users). 

He was wondering if this is something that should be documented somewhere, just as a reminder/warning for other teams in the future. Or is this use-case so niche that there isn't a whole lot of value of documenting it somewhere?

**Comment by Blackbaud-SteveBrush** [comment]
@Blackbaud-AliRashed Good idea! I think a good middle ground would be to add a new design guideline to the documentation that describes what a developer should do in this particular scenario. I've created a new issue to address this: https://github.com/blackbaud/skyux2-docs/issues/684
